apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: parking-system
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/smart_parking_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_PROFILES_ACTIVE: "docker"
