apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parking-ingress
  namespace: parking-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: parking.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
