apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: parking-system
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS smart_parking_db;
    CREATE USER IF NOT EXISTS 'parking_user'@'%' IDENTIFIED BY 'parking_pass';
    GRANT ALL PRIVILEGES ON smart_parking_db.* TO 'parking_user'@'%';
    FLUSH PRIVILEGES;
    ALTER USER 'parking_user'@'%' IDENTIFIED WITH mysql_native_password BY 'parking_pass';
